baseURL: "https://cottonlab-psy.github.io" 
title: COTTONLAB
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: RESEARCH
          url: research/
          weight: 1 
        - name: MEMBERS
          url: members/
          weight: 2 
        - name: PUBLICATIONS
          url: publications/
          weight: 3
        - name: JOIN US
          url: joinus/
          weight: 4 

params:
    description: "COgnition and aTTentiON lab @CBNU"
    author: COTTONLAB
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["RESEARCH", "MEMBERS", "PUBLICATIONS", "JOIN US"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    
    profileMode:
          enabled: true
          title: COTTON LAB @CBNU
          subtitle: >
            <img src="lab_logo.png" width = "300px" style = "margin-top: 20px;"><br>
            COgnition and aTTentiON lab @CBNU
          imageUrl: "lab_banner.png"
          imageWidth: 400
          imageHeight: 160
          buttons:
            - name: RESEARCH
              url: research/
            - name: MEMBERS
              url: members/
            - name: PUBLICATIONS
              url: publications/
            - name: JOIN US
              url: joinus/
              
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: ""
      icon: lab_banner.png
      iconHeight: 35

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
